"""
Pure Python utility to generate standardized GitHub PR markdown.
No LLM calls — this is a templating utility only.
"""


def generate_pr_body(vulnerability_type, cwe, severity, exploit_evidence, changes_made_list):
    """
    Generate a beautiful, standardized Markdown PR body.

    Args:
        vulnerability_type (str): e.g., "SQL Injection"
        cwe (str): e.g., "CWE-89"
        severity (str): e.g., "HIGH", "MEDIUM", "LOW"
        exploit_evidence (str): The proof-of-concept exploit output
        changes_made_list (list): List of bullet points explaining the fix

    Returns:
        str: Raw Markdown string for the PR body
    """

    # Determine severity badge color
    severity_lower = severity.lower()
    if severity_lower == "high":
        severity_badge = "🔴 HIGH"
    elif severity_lower == "medium":
        severity_badge = "🟠 MEDIUM"
    elif severity_lower == "low":
        severity_badge = "🟡 LOW"
    else:
        severity_badge = f"⚪ {severity.upper()}"

    # Build the markdown body
    md = f"""# 🔒 Security Patch: {vulnerability_type}

## 🚨 Vulnerability Summary

| Property | Value |
|----------|-------|
| **Vulnerability Type** | {vulnerability_type} |
| **CWE** | [{cwe}](https://cwe.mitre.org/data/definitions/{cwe.split('-')[1]}.html) |
| **Severity** | {severity_badge} |

This patch addresses a critical {vulnerability_type} vulnerability in the application code.

---

## 🛡️ The Fix

The following changes were made to neutralize the vulnerability:

"""

    # Add changes as bullet points
    for change in changes_made_list:
        md += f"- {change}\n"

    md += """
---

## 💥 Exploit Proof

**Original Vulnerability:** The following exploit successfully extracted sensitive data:

```python
"""

    md += exploit_evidence

    md += """
```

After this patch is applied, the above exploit will fail to extract sensitive data.

---

## 🤖 PatchOps Auto-Verification

This patch was generated and verified by the PatchOps autonomous security system:

- [x] **Code Analysis**: Vulnerability identified and classified
- [x] **Exploit Generation**: Proof-of-concept exploit created and executed
- [x] **Patch Authoring**: Secure fix generated and validated
- [x] **Security Review**: Patch reviewed for correctness and no new vulnerabilities
- [x] **Regression Testing**: Verified that the patch blocks the exploit without breaking functionality

---

## 📋 Merge Instructions

1. Review the code changes carefully
2. Run the application locally to verify functionality
3. Run any existing test suites to ensure no regressions
4. Merge when satisfied

---

*Generated by [PatchOps](https://github.com/gauravmishraokok/PatchOps) - Autonomous Security Patching*
"""

    return md
