"""
Dynamic Markdown generator for GitHub PR bodies.
Generates numbered lists of security patches based on array input.
"""


def generate_pr_body(fixed_vulnerabilities_list):
    """
    Dynamically generates a GitHub PR markdown body based on an array of fixes.
    
    Args:
        fixed_vulnerabilities_list (list): Array of vulnerability fix objects
            Each object should contain:
            - type: Vulnerability type (e.g., "SQL Injection")
            - cwe: CWE number (e.g., "CWE-89")
            - changes_made: List of change descriptions
            - exploit_evidence: Proof-of-concept or exploit code
    
    Returns:
        str: Raw Markdown string formatted for GitHub PR
    """
    if not fixed_vulnerabilities_list:
        return "## 🛡️ Security Patch\nNo vulnerabilities were provided for this patch."

    # Header
    markdown_body = f"# 🔒 Security Patch: {len(fixed_vulnerabilities_list)} Vulnerabilities Resolved\n\n"
    markdown_body += "This automated pull request applies surgical security patches generated by the **PatchOps Autonomous Pipeline**.\n\n"
    markdown_body += "---\n\n"
    
    # Dynamic Numbered List
    markdown_body += "## 📋 Summary of Fixes\n\n"
    
    for index, vuln in enumerate(fixed_vulnerabilities_list, start=1):
        vuln_type = vuln.get('type', 'Unknown Vulnerability')
        cwe = vuln.get('cwe', 'Unknown CWE')
        changes = vuln.get('changes_made', [])
        exploit = vuln.get('exploit_evidence', 'No exploit evidence provided.')
        
        # 1. Title with index
        markdown_body += f"### {index}. {vuln_type} ({cwe})\n\n"
        
        # 2. Changes Made (Brief List)
        markdown_body += "**Changes Made:**\n"
        if isinstance(changes, list) and changes:
            for change in changes:
                markdown_body += f"- {change}\n"
        else:
            markdown_body += f"- {changes}\n"
        
        markdown_body += "\n"
            
        # 3. Exploit Evidence (Collapsible)
        markdown_body += "<details>\n"
        markdown_body += "<summary><strong>🚨 View Exploit Proof</strong></summary>\n\n"
        markdown_body += "```python\n"
        markdown_body += f"{exploit}\n"
        markdown_body += "```\n\n"
        markdown_body += "</details>\n\n"
        
        markdown_body += "---\n\n"

    # Footer
    markdown_body += "### 🤖 PatchOps Auto-Verification\n\n"
    markdown_body += "- [x] Code Analysis: Vulnerabilities identified strictly within defined scope.\n"
    markdown_body += "- [x] Exploit Generation: Verified via sandbox execution.\n"
    markdown_body += "- [x] Patch Authoring: Surgical modifications applied.\n"
    markdown_body += "- [x] Regression Testing: Verified fixes do not break core functionality.\n\n"
    markdown_body += "*Generated autonomously by PatchOps.*"

    return markdown_body


    return md
